# Generated by Django 5.0.6 on 2024-05-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasty_ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dish_type',
            field=models.CharField(choices=[('sushi', 'cold dishes'), ('salad', 'warm dishes'), ('soup', 'warm dishes')], max_length=50),
        ),
    ]
