# Generated by Django 5.0.6 on 2024-05-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasty_ideas', '0005_alter_category_dish_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default_category_image.jpg', upload_to='category_images/'),
        ),
    ]
