# Generated by Django 5.0.6 on 2024-05-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasty_ideas', '0007_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
