# Generated by Django 5.0.6 on 2024-05-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasty_ideas', '0008_dish_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',)},
        ),
    ]
